### ISSUE TITLE
link state changes & suspend

### ISSUE THREAD

**Issue by leahneukirchen** [niklata/ndhc#6]
After unplugging ethernet while the machine is suspended, ndhc doesn't notice the interface doesn't have a carrier anymore and tries sending renew requests.  I fear this cannot be dealt with without polling (or an additional ioctl somewhere), as linux happily sendto(2)s to an interface without carrier...

**Comment by niklata** [comment]
Hmm... I'll need to see if there's a way of being notified about suspends from the kernel.  Alternatively, since renew/rebind/etc requests are infrequent (from a power-savings perspective), it's probably also not too costly to check for carrier via netlink before sending a message.  This would handle the carrier->nocarrier transition that happens during suspend.

For nocarrier->carrier during suspend, it will require either being notified by the kernel about suspends or polling, I think.

I'll have to look at the Linux/netlink interfaces a bit to decide what's best.  It seems like suspend notification should exist in some form...

**Comment by leahneukirchen** [comment]
At least for "eth0: Resetting IP configuration." there should be an explicit check of carrier I guess.
dhcpcd seems to use SIOCGIFFLAGS/SIOCGIFMEDIA which should be reasonably cheap.

**Comment by niklata** [comment]
A suspend/resume notification exists inside the kernel and must be exported to userspace somewhere (perhaps via uevents) as pm_utils and systemd have notification interfaces.  I'll dig around and find the correct method.

**Comment by niklata** [comment]
ndhc now checks for carrier before sending data on the interface fd for unicast/broadcast/arp.  If it doesn't have a carrier, it simulates the sendto/write failing.  For now this uses ioctl, but could be converted to a blocking request to ifchd which could service the query via netlink requests.  The advantage there would be avoiding the need to whitelist ioctl for seccomp.

I haven't yet found a good interface to find out that the kernel has resumed.  There's the awful hack of checking for timestamp slew by writing timestamps periodically to a pipe and reading out the values to detect the gap that a suspend would cause, but such a method requires constant polling which I want to avoid.

I'm not sure if the kernel provides a nice pollable notification mechanism to detect resumes, though.

**Comment by niklata** [comment]
I've just pushed a set of changesets that convert ndhc from using callbacks and multiple state machines to using a coroutine.  Error handling was made more robust and some unrelated bugs were fixed at the same time.

It's likely that the behavior of ndhc has changed with respect to rfkill, link carrier change, and suspend.

The new changes work on my (wired ethernet, never suspended) test machines, but I may have also introduced some new bugs.

Please let me know how it works for you.

**Comment by niklata** [comment]
The caching of carrier state has been removed and instead carrier status is checked on the spot whenever it is required.  I believe these problems should be gone, but please just open another bug if a problem remains.
