### ISSUE TITLE
resolv.conf.head and resolv.conf.tail

### ISSUE THREAD

**Issue by jsumners** [niklata/ndhc#8]
It seems like ISC's dhcpcd has support for prepending a `/etc/resolv.conf.head` and appending a `/etc/resolv.conf.tail` when it writes out `/etc/resolv.conf`. Support for this in `ndhc` would be very nice.

**Comment by niklata** [comment]
I've pushed a commit to master that should use these files if they exist.  I've not run-tested the commit, only compiled it and examined it so that I believe it is correct, so please test and report if there are any issues.

It should require no configuration change; these files will be detected at initialization time and will be used if they exist.  Because of the way this functions, these files will continue to be used even if they are deleted while ndhc is running; this is the only notable quirk (necessary because ifchd runs in a chroot) that probably differs from dhcpcd.

Note this also makes it somewhat dangerous to update these files while ndhc is running, as the posix-atomicity trick of relinking the file via eg, mv will not work.  The failure case here is that there would exist a small race while the contents of the file would be inconsistent from partial writes.

If everything is fine then I will update the documentation, too.

**Comment by jsumners** [comment]
I will give a try this weekend. Thank you for the quick update.

**Comment by jsumners** [comment]
Just got a chance to try it out. It worked great.

Can I ask one more favor? Tag releases so that they're easier to grab. It was fun times getting the tarballs and sha256sums to update the Void Linux package script in a VM without copy and paste support -- https://github.com/voidlinux/void-packages/blob/master/srcpkgs/ndhc/template#L26

Even a tag like "2016-05-09" would be great.

BTW, thank you for the great tool. I can't stand ISC's outdated software and I love the jail feature to an IP from my ISP.

**Comment by niklata** [comment]
Glad to hear that it works fine, and that you are satisfied with ndhc!

I've tagged a snapshot for release at https://github.com/niklata/ndhc/releases/tag/v2016-05-06 .  Probably I will also provide gpg signatures for verification at some point, but I'll have to decide on the best way to distribute them.  I don't want to sign every commit, but doing so at regular intervals that I also tag as releases would provide more assurance against repo tampering than just the git rolling sha sums.

**Comment by jsumners** [comment]
Awesome. And it looks like the Void package maintainer has already updated the package (I was going to submit a PR to them).

This issue is resolved as far as I'm concerned.
